---
title: "DB Method"
author: "Kinh Nguyen"
date: "`r Sys.Date()`"
params:
  country: "Senegal"
  sex: 2
---

```{r include=FALSE, message=FALSE, warning=FALSE}
library(ktools)
library(TMB)
library(dplyr)
library(loo)
library(data.table)
library(knitr)
library(survey)
library(tidyverse)

set.seed(123)
```

```{r}
# sexual debut data
# ssa = data.table::fread("data/SSA_AFS.csv.bz2")

# TMB model
compile('model.cpp')
dyn.load(dynlib('model'))
openmp(4)
invisible(config(tape.parallel=FALSE, DLL='model'))

# sample posterior
source("tmb_sampling.R")
source("get_predict.R")
```

# `r params$country` data of sex `r params$sex`

```{r}
sexes <- c('male', 'female')
params <- list(sex=1, country="Guinea")


get_pars <- function(sexid=1, iso2 = "ET", skewit = 1) 
{
  di <- filter(dtab, iso == iso2 & sex == sexes[sexid])
 
  fitdt = di %>% 
    mutate(afs = as.numeric(afs), event = as.integer(event),
           afs = if_else(event==0, age, afs))
  
  yob_u <- fitdt %>% pull(yob) %>% unique() %>% sort()
  age_u <- fitdt %>% pull(age) %>% unique() %>% sort()
  
  o = get_predict(to_skew = skewit, weightv = "kish", 
                  yob_term = 1, smooth_yob = 1, 
                  age_term = 1, smooth_age = 1, 
                  data = fitdt)

  o <- o %>% 
    as_tibble(.name_repair = "universal") %>% 
    select(-log_yob_rw2_e, -log_age_rw2_e) %>%
    rename_with(~paste0("y_", yob_u), starts_with("yob_rw2")) %>%
    rename_with(~paste0("a_", age_u), starts_with("age_rw2")) %>%
    mutate(smp = 1:n()) %>% 
    pivot_longer(starts_with('y_'), names_to = c(NA, 'yob'), values_to = "yobc", 
                 names_sep = "_", names_transform = list(yob = as.integer)) %>%
    pivot_longer(starts_with('a_'), names_to = c(NA, 'age'), values_to = "agec", 
                 names_sep = "_", names_transform = list(age = as.integer)) %>% 
    mutate(
      shape = exp(log_shape),
      scale = exp(intercept + yobc + agec)
    )
  if (skewit)
    o <- mutate(o, skew = exp(log_skew))
  else
    o <- mutate(o, skew = 1)
  o
}
```

# Survey design

```{r}
design <- di %>% 
  filter(afs!=0) %>% 
  svydesign(
  id      = .$psu, 
  strata  = .$strata, 
  weights = .$weights,
  data    = ., 
  nest    = TRUE
)

afsby <- svyby(
  formula = ~afs, 
  by      = ~lab + yob, 
  design  = design, 
  FUN     = svymean, 
  vartype = "ci"
)
```


# Fitting

# Plot

```{r}
pn <- bind_rows(
  get_pars(sexid = 1, iso2 = "GN"),
  get_pars(sexid = 1, iso2 = "ZM"),
  get_pars(sexid = 2, iso2 = "ET"),
  get_pars(sexid = 2, iso2 = "SN"),
  .id = "iso"
  ) %>% 
  mutate(iso = as.integer(iso), iso = c("GN", "ZM", "ET", "SN")[iso])

ps <- bind_rows(
  get_pars(sexid = 1, iso2 = "GN", skewit = 0),
  get_pars(sexid = 1, iso2 = "ZM", skewit = 0),
  get_pars(sexid = 2, iso2 = "ET", skewit = 0),
  get_pars(sexid = 2, iso2 = "SN", skewit = 0),
  .id = "iso"
  ) %>% 
  mutate(iso = as.integer(iso), iso = c("GN", "ZM", "ET", "SN")[iso])

pns <- bind_rows(
   pn %>% select(iso, smp, yob, age, scale, shape, skew), 
   ps %>% select(iso, smp, yob, age, scale, shape, skew),
   .id = "version") %>% 
  mutate(version = as.integer(version), version = c("Skew", "Non")[version])
 
```

## Median plot

```{r}
pns %>% 
  filter(age==23 & version=="Skew") %>%
  mutate(med = qskewlogis(.5, scale, shape, skew)) %>% 
  group_by(version, iso, yob, age) %>%
  summarise(
    afs  = median(med), 
    ci_u = quantile(med, .975),
    ci_l = quantile(med, .025)) %>% 
  mutate(sex = case_when(iso=="ET" ~ "Female",
                         iso=="GN" ~ "Male", 
                         iso=="SN" ~ "Female",
                         TRUE ~ "Male"),
         iso = iso2name(iso)) %>% 
  ggplot() +
  geom_ribbon(aes(yob, afs, ymin=ci_l, ymax=ci_u, fill=iso), alpha=.3) +
  geom_line(aes(yob, afs, color=iso, linetype=sex), size=1.1) +
  labs(x = "Birth cohort", y = "Median AFS", fill="", linetype="") +
  scale_fill_viridis_d(end=.9) +
  scale_color_viridis_d(end=.9) +
  coord_cartesian(expand=FALSE) +
  theme_bw() +
  guides(color="none") +
  labs(title="Median AFS", subtitle="(respondent age 23)") +
  theme(
    strip.background  = element_rect(fill='grey95', color = 'grey70', size = .3), 
    panel.border      = element_rect(color = 'grey70'),
    # legend.position   = 'c(.85, .4)',
    legend.background = element_rect(fill = NA)
    ) -> g1
```

## density plot

```{r}
ed <- pns %>% 
  group_by(version, iso) %>% 
  filter(yob == max(yob) & age==23 & smp == 1) %>% 
  uncount(length(agex), .id = 'age') %>% 
  mutate(age = age*.1 + 9.9, 
         dens = dskewlogis(age, scale, shape, skew),
         sex = case_when(iso=="ET" ~ "Female",
                         iso=="GN" ~ "Male", 
                         iso=="SN" ~ "Female",
                         TRUE ~ "Male"),
         iso = iso2name(iso))

ed %>% 
  filter(version=="Skew") %>% 
  ggplot() +
  geom_line(aes(age, dens, color=iso, fill=iso, linetype=sex), size=1.1) +
  scale_color_viridis_d(end=.9) +
  labs(title="Estimated density", subtitle="(birth cohort 1989)",  color="", y="Density", x="Age", linetype="") +
  coord_cartesian(xlim=c(10, 30)) + 
  theme_bw() +
  theme(
    strip.background  = element_rect(fill='grey95', color = 'grey70', size = .3), 
    panel.border      = element_rect(color = 'grey70'),
    legend.background = element_rect(fill = NA)
    ) -> g2
```

## age at report plot

```{r}
pns <- bind_rows(
   pn %>% select(iso, smp, yob, age, scale, shape, skew), 
   ps %>% select(iso, smp, yob, age, scale, shape, skew),
   .id = "version") %>% 
  mutate(version = as.integer(version), version = c("Skew", "Non")[version])
 
pn %>% 
  filter(yob == 1989 & smp == 1) %>% 
  mutate(sex = case_when(iso=="ET" ~ "Female",
                         iso=="GN" ~ "Male", 
                         iso=="SN" ~ "Female",
                         TRUE ~ "Male"),
         iso = iso2name(iso)) %>%
  ggplot() +
  geom_line(aes(age, -agec, color=iso, fill=iso, linetype=sex), size=1.1) +
  scale_color_viridis_d(end=.9) +
  labs(title="Age at report effect", subtitle="(on AFS's central parameter)", color="", y="Coefficient", x="Age", linetype="") +
  theme_bw() +
  theme(
    strip.background  = element_rect(fill='grey95', color = 'grey70', size = .3), 
    panel.border      = element_rect(color = 'grey70'),
    legend.background = element_rect(fill = NA)
    ) -> g3
```

## Cumulative density

```{r}
ed %>% 
  filter(version=="Skew") %>% 
  mutate(dens = ktools::pskewlogis(age, scale, shape, skew)) %>% 
  ggplot() +
  geom_line(aes(age, dens, color=iso, fill=iso, linetype=sex), size=1.1) +
  scale_color_viridis_d(end=.9) +
  labs(title="Estimated cumulative density", subtitle="(birth cohort 1989)",  color="", y="Density", x="Age", linetype="") +
  coord_cartesian(xlim=c(10, 30)) + 
  theme_bw() +
  theme(
    strip.background  = element_rect(fill='grey95', color = 'grey70', size = .3), 
    panel.border      = element_rect(color = 'grey70'),
    legend.background = element_rect(fill = NA)
  ) -> g4
```

## Combined plot

```{r}
library(ggpubr)
g12 <- ggarrange(g1, g3, g2, g4, ncol=2, nrow=2, common.legend = TRUE, legend = "bottom")
# ggarrange(ggarrange(g1, g2, ncol=2, common.legend = 1), g3, nrow=2, common.legend = TRUE, legend = "bottom")
quartz_off(g12, name = "median_density", 7, 7, open=1)

```