---
title: "DB Method"
author: "Kinh Nguyen"
date: "`r Sys.Date()`"
params:
  nsv: 3
  sample_size: 1000
  bias: "none"
  trend: "none"
  theK: 100
---

```{r include=FALSE, message=FALSE, warning=FALSE}
# params = list(nsv=2, sample_size=1000, bias='none', trend='increase')

library(abind)
library(TMB)
library(data.table)
library(tidyverse)
# remotes::install_github('kklot/ktools')
library(ktools)
library(loo)                # 

save_to = "outputs_men_women/"
# Check if input from bash is correct
myname = unlist(params) %>% paste0(names(.), .) %>% paste0(collapse="_") %>% paste0(".rds")
myname = paste0(save_to, myname)
if (file.exists(myname))
	stop("did it")
message(myname)

set.seed(123)
options(mc.cores = parallel::detectCores()-2)
```

## Pool population

```{r}
N <- 10^6
birth_cohorts <- 1940:2005
wanted_cohort <- 1970:2005
elig_age      <- 15:49 # age eligible for including in the year of surveys

# take age distribution of SZ
sz = data.frame(
    age = c(
        15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49
    ),
    n = c(
        525, 566, 514, 469, 443, 464, 351, 385, 321, 316, 262, 301, 273, 241,
        222, 245, 211, 188, 184, 185, 151, 184, 164, 235, 123, 151, 136, 144,
        109, 116, 108, 136, 124, 136, 81
    )
)

sz %>% {approxfun(.[,1], .[,2]/sum(.[,2]), yleft=0, yright=0)} -> age_weight

my_pop <- data.table(id  = 1:N, yob = sample(birth_cohorts, N, T), afs=0)
```

# Load dll

```{r}
openmp(1) # we do multiple fit on parallel so avoiding using it in TMB
compile('model.cpp')
dyn.load(dynlib('model'))
invisible(config(tape.parallel=FALSE, DLL='model'))

source("tmb_sampling.R")
```

# AFS parameters and sampling

Following skew log-logistic distribution, at the begining, year 1900

```{r}
ref = list(scale = 0.06204, shape = 10, skew  = 1.5)
qskewlogis(.5, ref$scale, ref$shape, ref$skew) 
min_scale = 0.0703  # 15
qskewlogis(.5, min_scale, ref$shape, ref$skew) 
max_scale = 0.05859 # 18
qskewlogis(.5, max_scale, ref$shape, ref$skew) 

if (params$trend == "none") {
	pdata = tibble(yob = birth_cohorts, scale = ref$scale, skew = ref$skew, shape = ref$shape)
} else if (params$trend == "increase") {
	scalev = seq(min_scale, max_scale, length.out = length(birth_cohorts))
	pdata  = tibble(yob = birth_cohorts, scale = scalev, skew = ref$skew, shape = ref$shape)
} else if (params$trend == "decrease") {
	scalev = seq(max_scale, min_scale, length.out = length(birth_cohorts))
	pdata  = tibble(yob = birth_cohorts, scale = scalev, skew = ref$skew, shape = ref$shape)
}

## Generate true afs
afsd = my_pop %>% 
	left_join(pdata, "yob") %>% 
  arrange(yob) %>% 
  group_by(yob) %>% 
  mutate(afs = rskewlogis(n(), scale, shape, skew)) %>% 
  select(id, yob, afs)
```

# Generate biases

```{r}
bias_none = function(age) 0
bias_norm = function(age, sd = 0.3) rnorm(1, 0, sd)
bias_logis = function(age, max = 4, r = .5, mid = 23) max / (1 + exp(-r*(age - mid))) - max/2

bias_lgt = function(age, mid=23, maxx=4.5, r=.4) maxx / (1 + exp(-r * (age - mid))) - 2
bias_women = function(age) .5 - bias_lgt(age, ,2.5) 
bias_men = function(age) .5 + bias_lgt(age, r = .25) 

if (params$bias == "none") bias_f = bias_none
if (params$bias == "norm") bias_f = bias_norm
if (params$bias == "logis") bias_f = bias_logis
if (params$bias == "men") bias_f = bias_men
if (params$bias == "women") bias_f = bias_women

plott(bias_f(15:49))
```

# Generate survey data

```{r}
afsd = afsd %>%
  uncount(params$nsv, .id = "svy") %>% 
  mutate(svy = 2000 + 5 * (svy - 1))  %>% 
  mutate(age = svy - yob) %>%
	filter(age %in% 15:49) %>% 
  mutate(bias = bias_f(age) + rnorm(n(), 0, 0.3), biased_afs = afs + bias) %>% 
  mutate(weight = age_weight(age)) %>% 
  mutate(event = if_else(biased_afs <= age, 1, 0))
```

# Fit model

```{r get_post}
source("get_posterior.R")
 
# parallel
post = get_posterior(data=afsd, sample_size=params$sample_size, K=params$theK)
attributes(post)$ref_par = ref 

# saveRDS(post, paste0("post/", myname))
```

# Get some stats

```{r get_stat}
X = attributes
pdata %<>% mutate(median = qskewlogis(.5, scale, shape, skew))

# apply to one scenario with 1000 posterior samples
# x = post[[1]]
stats = function(x, agref = 1) {
	realskew = x[, 'log_skew'] %>% exp
	realshape = x[, 'log_shape'] %>% exp
	ageref  = tibble(age=X(x)$age, id=X(x)$age_id) %>% mutate(agr = findInterval(age, seq(15, 50, 5))) 
	agecoef = x[, ageref %>% filter(agr==agref) %>% pull(id)] %>% rowMeans
	realscale = exp(sweep(x[, X(x)$yob_id], 1, x[, 'intercept'], '+') + agecoef) 

	getmed = function(y, x) {
		medx = qskewlogis(.5, realscale[y, ], realshape[y], realskew[y]) %>% 
			tibble(med = ., yob = X(x)$yob) %>% 
			left_join(pdata, 'yob')  %>% 
			select(yob, med, median) %>% 
			filter(row_number() == 1 | row_number() == max(row_number()))  %>% 
			mutate(diff  = med - median)  
		tibble(first_diff = medx$diff[1], 
					 last_diff = medx$diff[2], 
					 trend_diff = medx$med[2] - medx$med[1], 
					 real_diff = medx$median[2] - medx$median[1], 
		)
	}

	st = lapply(1:params$theK, getmed, x = x) %>% bind_rows()  

	tr = st %>%  
		mutate(increase = trend_diff > 0) %>% 
		group_by(increase) %>% 
		summarise(n = n(), 
							trend_diff = mean(trend_diff), 
							.groups = 'drop')  

	tibble(first_diff = mean(st$first_diff), 
				 last_diff = mean(st$last_diff), 
				 trend_diff = mean(st$trend_diff), 
				 pc_increase = tr$n[2]/(tr$n[1] + tr$n[2]), 
				 trend_diff_real = st$real_diff[1], 
				 trend_diff_pos = tr$trend_diff[2], 
				 trend_diff_neg = tr$trend_diff[1])

}

# tata = getstats (1)
getstats = function(aref) 
{
	parallel::mclapply(post, stats, agref = aref)  %>% 
		bind_rows(.id = 'sample')  %>% 
		mutate(ageref = aref, nsv = params$nsv, size = params$sample_size, 
					 trend = params$trend, bias = params$bias, nsample = params$theK) 
}
	
out1 = getstats(1)
out2 = getstats(2)
out3 = getstats(3)
out4 = getstats(4)

out = bind_rows(out1, out2, out3, out4)

saveRDS(out, myname)
```

